apiVersion: v1
kind: Secret
metadata:
  name: {{ include "config-service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "config-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.db.url | quote }}
